# Generated by Django 5.1 on 2024-11-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamland_app', '0002_alter_configuration_built_up_area_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Propertie',
        ),
    ]
