# Generated by Django 5.1 on 2025-01-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreamland_app", "0013_alter_propertyimage_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
